// Generates supabase/seed.sql from the same seed data the demo mode uses.
// Run: npx tsx scripts/seed-sql.ts > supabase/seed.sql
import { seedData } from '../src/data/seed';
import { toServer } from '../src/data/sync';

const { club, teams, players, history } = seedData(Date.UTC(2026, 9, 5));
const lit = (v: unknown): string => {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  if (Array.isArray(v)) return `array[${v.map(lit).join(',')}]::text[]`;
  if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};
const insert = (table: string, rows: object[]) => {
  for (const r of rows) {
    const o = toServer(r as Record<string, unknown>);
    console.log(`insert into ${table} (${Object.keys(o).join(', ')}) values (${Object.values(o).map(lit).join(', ')}) on conflict (id) do nothing;`);
  }
};
console.log('-- Melita FC demo data (generated by scripts/seed-sql.ts). Users/memberships are created by invitation.');
insert('clubs', [club]);
insert('teams', teams);
insert('players', players);
console.log(`-- Make yourself Club Admin: sign-up with this email (or change it) and the trigger creates the membership.`);
console.log(`insert into invitations (id, club_id, email, role, team_ids, age_groups, invited_by, updated_at) values ('inv-first-admin', 'club-melita', 'admin@example.com', 'club_admin', '{}', '{}', 'seed', 0) on conflict (id) do nothing;`);
console.log(`insert into invitations (id, club_id, email, role, team_ids, age_groups, invited_by, updated_at) values ('inv-u14-coach', 'club-melita', 'coach@example.com', 'coach', array['team-melita-u14'], '{}', 'seed', 0) on conflict (id) do nothing;`);
